### PR TITLE
Fix Word256 Prim alignment. Fix #40

### LINKED ISSUE #40: Alignment Word256
`Storable` and `Prim` instances have mismatching alignment values for `Word256`.
* Storable is 32 bytes
* Prim is 8 bytes.

### PR DESCRIPTION
**Pull request by lehins**

### CODE REVIEW

**Comment by erikd** [comment]
Fixing this is great, but I would really like to see a test added that fails without this commit and passes with it.

**Comment by lehins** [comment]
I know how you feel my friend. :) But, you see, that is exactly how I found this bug. I used `wide-word` for testing the new package [pvar](https://github.com/lehins/pvar) that I just released and the tests that I came up with have failed. So, I did my dues, I reported and even fixed the bug. But if you'd like to see some tests, seem like you need to do your dues ;)

**Comment by erikd** [comment]
@chessai I notice that `tests/laws.hs` has tests for for the `Storable` typeclass, but that did not detect this bug. I have switched from `arbitrary` to `arbitraryBoundedIntegral` on the generators but this is still undetectable. Wouldn't that suggest that the Laws for `Storable` are incomplete?

**Comment by erikd** [comment]
@chessai Looking at https://hackage.haskell.org/package/quickcheck-classes-0.6.4.0/docs/Test-QuickCheck-Classes.html#v:storableLaws I think:
```
    (pokeElemOff ptr ix a >> peekElemOff ptr ix') ≡ pure a
```
is in sufficient. It doesn't detect the possibility of the `Storable`'s offset being wrong.

**Comment by erikd** [comment]
The `Storable` laws can't detect this error, I will write a dedicated test for this.

**Comment by chessai** [comment]
@erikd hmm interesting. whatever test you write i will `peek` something off and `poke` it into those tests so we can maybe be able to catch something like this.

**Comment by erikd** [comment]
@lehins I have a slightly better fix for this in #45, but thanks for bringing this to my attention

**Comment by erikd** [comment]
Travis is currently down. I am going to wait for it to be back up and run this CI job before merging.

**Pull request closed without merging**
