### PR TITLE
Derive Data, Typeable, and Ix instances.

### PR DESCRIPTION
**Pull request by dhess**

### CODE REVIEW

**Comment by dhess** [comment]
I added `Ix`, as well. With these changes, `Word128`'s typeclass instances are nearly identical to those of the `base` `WordN` types.

**Comment by erikd** [comment]
Thanks!

**Comment by lehins** [comment]
What is the point of deriving `Typeable` if every data type since ghc-7.10 (which is the earliest supported by `wide-word`) has an instance of by default?

**Comment by erikd** [comment]
Yeah probably redundant, but not a problem.

**Comment by lehins** [comment]
That is true, since:
> Derived instances of `Typeable` may be declared if the `DeriveDataTypeable` extension is enabled, but they are ignored, 

unless ghc developers will decide to follow [the documentation](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html?highlight=derivedatatypeable#deriving-typeable-instances) at some point in the future:
> and they may be reported as an error in a later version of the compiler.

**Comment by dhess** [comment]
@lehins I added in case the author ever wanted to support an earlier version, and because there's no cost to do so.

**Comment by lehins** [comment]
@dhess It's all good. It doesn't really matter to me, I just wanted to point out that `Typeable` instance is redundant. Thank you for your contribution.

**Pull request merged**
