### PR TITLE
Add cases for arch with word size less than 64 bit.

### LINKED ISSUE #36: Compliation for ARM fails
I tried to use the library for our mobile app and getting the following errors at build time for `androideabi-ghc-8.6.5` platform:

```
[1 of 3] Compiling Data.WideWord.Word128 ( src/Data/WideWord/Word128.hs, dist/build/Data/WideWord/Word128.o )

src/Data/WideWord/Word128.hs:173:79: error:
    • Couldn't match expected type ‘ghc-prim-0.5.3:GHC.Prim.Word64#’
                  with actual type ‘ghc-prim-0.5.3:GHC.Prim.Word#’
    • In the first argument of ‘W64#’, namely ‘0##’
      In the first argument of ‘Word128’, namely ‘(W64# 0##)’
      In the expression: Word128 (W64# 0##) (W64# (int2Word# i#))
    |
173 | "fromIntegral :: Int -> Word128"     fromIntegral = \(I# i#) -> Word128 (W64# 0##) (W64# (int2Word# i#))
    |                                                                               ^^^

src/Data/WideWord/Word128.hs:173:91: error:
    • Couldn't match expected type ‘ghc-prim-0.5.3:GHC.Prim.Word64#’
                  with actual type ‘ghc-prim-0.5.3:GHC.Prim.Word#’
    • In the first argument of ‘W64#’, namely ‘(int2Word# i#)’
      In the second argument of ‘Word128’, namely ‘(W64# (int2Word# i#))’
      In the expression: Word128 (W64# 0##) (W64# (int2Word# i#))
    |
173 | "fromIntegral :: Int -> Word128"     fromIntegral = \(I# i#) -> Word128 (W64# 0##) (W64# (int2Word# i#))
    |                                                                                           ^^^^^^^^^^^^
```

Here the full log of build and full toolchain:
https://travis-ci.com/hexresearch/ergvein/jobs/288072584#L5513

P.S. Sorry that I don't have a concise example of the fail.

### PR DESCRIPTION
**Pull request by NCrashed**
Fix #36. It is not so beauty with added conversion everywhere, but it is as close to the original as possible.

### CODE REVIEW

**Comment by erikd** [comment]
Scattering `#ifdef`s throughout the code is a solution (and probably the most obvious one), but almost certainly not the best solution. Let me ponder this.

**Comment by NCrashed** [comment]
So, take your time. I needed a fast fix to continue development of our project :)

I don't insist on merging this, just sharing my solution with others. We will switch to the original repo as soon as a better fix is available.

**Comment by erikd** [comment]
This issue is problematic. The fix in this PR (or basically any fix) would be likely to break on the first change after it is merged. The only way to prevent that is a 32 bit CI job.

Unfortunately Travis does not offer 32 bit CI. See https://github.com/travis-ci/travis-ci/issues/986

**Comment by erikd** [comment]
This is still on hold while I try and figure out a 32 bit CI solution.

However, I wonder if using something like this:
```
#include "MachDeps.h"
#if WORD_SIZE_IN_BITS < 64
import GHC.IntWord64
#endif
```
might make maintaining the 32 bit support trivial and probably un-needed for 32 bit systems.

Would you be able to try this? I don't even have access to a 32 bit system.

**Comment by erikd** [comment]
Actually commit https://github.com/erikd/wide-word/commit/ff6e7b8446a285cef8ee7e340c761fcf8f83ae04 might even have fixed this. Please test.

**Comment by erikd** [comment]
Looks like i have 32 bit CI: https://github.com/haskell-works/wide-word/pull/2

**Comment by NCrashed** [comment]
> Actually commit [ff6e7b8](https://github.com/erikd/wide-word/commit/ff6e7b8446a285cef8ee7e340c761fcf8f83ae04) might even have fixed this. Please test.

The commit fails with:
```
src/Data/WideWord/Word128.hs:53:1: error:
    Could not load module ‘GHC.IntWord64’
    It is a member of the hidden package ‘ghc-prim-0.5.3’.
    Perhaps you need to add ‘ghc-prim’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
53 | import GHC.IntWord64
   | ^^^^^^
```

**Comment by NCrashed** [comment]
I also tried head of https://github.com/erikd/wide-word/tree/erikd/32-bit branch:
```
src/Data/WideWord/Word128.hs:258:17: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the first argument of ‘W64#’, namely ‘d1’
      In the first argument of ‘Word128’, namely ‘(W64# d1)’
      In the expression: Word128 (W64# d1) (W64# d0)
    |
258 |   Word128 (W64# d1) (W64# d0)
    |                 ^^

src/Data/WideWord/Word128.hs:258:27: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the first argument of ‘W64#’, namely ‘d0’
      In the second argument of ‘Word128’, namely ‘(W64# d0)’
      In the expression: Word128 (W64# d1) (W64# d0)
    |
258 |   Word128 (W64# d1) (W64# d0)
    |                           ^^

src/Data/WideWord/Word128.hs:260:31: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
    • In the first argument of ‘subWordC#’, namely ‘a0’
      In the expression: subWordC# a0 b0
      In a pattern binding: !(# d0, c1 #) = subWordC# a0 b0
    |
260 |     !(# d0, c1 #) = subWordC# a0 b0
    |                               ^^

src/Data/WideWord/Word128.hs:260:34: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
    • In the second argument of ‘subWordC#’, namely ‘b0’
      In the expression: subWordC# a0 b0
      In a pattern binding: !(# d0, c1 #) = subWordC# a0 b0
    |
260 |     !(# d0, c1 #) = subWordC# a0 b0

```

**Comment by Heinrich-CH** [comment]
Thank you for fix #36! Been stuck on this one for a few days!

**Comment by erikd** [comment]
@Heinrich-CH the fix for #36 should be on Hackage already.

**Comment by andrewthad** [comment]
I'm not convinced that the approach taken in this PR works. I've not seen the function `word64ToWord :: Word64# -> Word#` because I haven't written high-performance code for 32-bit systems, but certainly the only behavior this function could possibly have is to narrow its argument. So I'm not convinced that these changes actually work. Look at `plus128` for example. Running the test suite would be the way to know for sure.

More generally, I think the approach of putting CPP in the file makes it significantly more difficult for anyone to contribute in the future. My preference is using cabal for platform detection to swap out entire modules at a time.

**Comment by erikd** [comment]
@andrewthad I agree. I have no problem with small and trivial uses of `CPP` but something like this is going to become and unmaintainable mess very quickly.

**Comment by iliastsi** [comment]
Hey @erikd, is there any progress on this? wide-word currently fails to build on any 32-bit architecture (see https://buildd.debian.org/status/package.php?p=haskell-wide-word&suite=sid) and we have trouble updating it in Debian.

**Comment by erikd** [comment]
@iliastsi The main problem is that the solution in this PR is that it is incredibly hacky and will make maintenance significantly more difficult than it should be.

**Comment by iliastsi** [comment]
@erikd Thanks for looking into this. I was about to backport this PR to Debian, but I can wait a little bit longer for https://github.com/erikd/wide-word/pull/67. Let me know if I can help with testing.

**Comment by erikd** [comment]
Version `0.1.4.0` is on Hackage and compiles and passes all tests on 32 bit systems with `ghc >= 9.2`. Earlier versions are not supported because earlier versions of GHC are missing the required primops.

**Pull request closed without merging**
